#ifndef LEZ_MULTISIG_H
#define LEZ_MULTISIG_H

/* Auto-generated by cbindgen. Do not edit manually. */


#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new M-of-N multisig.
 *
 * args_json: {"threshold": u32, "members": [hex_pubkey, ...], "create_key": hex32,
 *             "program_id_hex": hex64, "wallet_path": "/path/to/wallet"}
 * Returns: {"success": true, "tx_hash": "..."}
 */
char *lez_multisig_create(const char *args_json);

/**
 * Submit a transaction proposal to a multisig.
 *
 * args_json: {"create_key": hex32, "program_id_hex": hex64, "wallet_path": "...",
 *             "pda_seeds": [...], "payload": {...}}
 * Returns: {"success": true, "tx_hash": "...", "proposal_index": u64}
 */
char *lez_multisig_propose(const char *args_json);

/**
 * Approve a pending proposal.
 *
 * args_json: {"create_key": hex32, "proposal_index": u64,
 *             "program_id_hex": hex64, "wallet_path": "..."}
 * Returns: {"success": true, "tx_hash": "..."}
 */
char *lez_multisig_approve(const char *args_json);

/**
 * Reject a pending proposal.
 *
 * args_json: {"create_key": hex32, "proposal_index": u64,
 *             "program_id_hex": hex64, "wallet_path": "..."}
 * Returns: {"success": true, "tx_hash": "..."}
 */
char *lez_multisig_reject(const char *args_json);

/**
 * Execute an approved proposal.
 *
 * args_json: {"create_key": hex32, "proposal_index": u64,
 *             "program_id_hex": hex64, "wallet_path": "..."}
 * Returns: {"success": true, "tx_hash": "..."}
 */
char *lez_multisig_execute(const char *args_json);

/**
 * Free a string returned by any lez_multisig_* function.
 * Must be called exactly once per returned pointer. Do NOT pass to libc free().
 */
void lez_multisig_free_string(char *s);

/**
 * Return the library version string as a JSON object.
 * Returns: {"version": "x.y.z"}  — caller must free with lez_multisig_free_string.
 */
char *lez_multisig_version(void);

/**
 * Return the program IDL (JSON schema) as a string.
 * Returns: the raw IDL JSON — caller must free with lez_multisig_free_string.
 */
char *lez_multisig_get_idl(void);

/**
 * List all proposals for a multisig.
 *
 * args_json: {"multisig_state": "<account_id>", "program_id_hex": hex64,
 *             "wallet_path": "..."}
 * Returns: {"success": true, "proposals": [{index, status, proposer, approvals,
 *           rejections, threshold}, ...]}
 */
char *lez_multisig_list_proposals(const char *args_json);

/**
 * Get the current state of a multisig.
 *
 * args_json: {"create_key": hex32, "program_id_hex": hex64, "wallet_path": "..."}
 * Returns: {"success": true, "threshold": u32, "member_count": u32,
 *           "members": [hex_pubkey, ...], "transaction_index": u64,
 *           "multisig_state_id": "<account_id>"}
 */
char *lez_multisig_get_state(const char *args_json);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LEZ_MULTISIG_H */
