#ifndef LEZ_MULTISIG_H
#define LEZ_MULTISIG_H

/* Auto-generated by cbindgen. Do not edit manually. */


#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

char *lez_multisig_create(const char *args_json);

char *lez_multisig_propose(const char *args_json);

char *lez_multisig_approve(const char *args_json);

char *lez_multisig_reject(const char *args_json);

char *lez_multisig_execute(const char *args_json);

void lez_multisig_free_string(char *s);

char *lez_multisig_version(void);

char *lez_multisig_get_idl(void);

char *lez_multisig_list_proposals(const char *args_json);

char *lez_multisig_get_state(const char *args_json);

/**
 * FFI: create_multisig instruction.
 */
char *multisig_program_create_multisig(const char *args_json);

/**
 * FFI: propose instruction.
 */
char *multisig_program_propose(const char *args_json);

/**
 * FFI: approve instruction.
 */
char *multisig_program_approve(const char *args_json);

/**
 * FFI: reject instruction.
 */
char *multisig_program_reject(const char *args_json);

/**
 * FFI: execute instruction.
 */
char *multisig_program_execute(const char *args_json);

/**
 * FFI: propose_add_member instruction.
 */
char *multisig_program_propose_add_member(const char *args_json);

/**
 * FFI: propose_remove_member instruction.
 */
char *multisig_program_propose_remove_member(const char *args_json);

/**
 * FFI: propose_change_threshold instruction.
 */
char *multisig_program_propose_change_threshold(const char *args_json);

void multisig_program_free_string(char *s);

char *multisig_program_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LEZ_MULTISIG_H */
