#ifndef LEZ_MULTISIG_H
#define LEZ_MULTISIG_H

/* Generated with cbindgen:0.29.2 */

/* Auto-generated by cbindgen. Do not edit manually. */


#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

char *lez_multisig_create(const char *args_json);

char *lez_multisig_propose(const char *args_json);

char *lez_multisig_approve(const char *args_json);

char *lez_multisig_reject(const char *args_json);

char *lez_multisig_execute(const char *args_json);

void lez_multisig_free_string(char *s);

char *lez_multisig_version(void);

char *lez_multisig_get_idl(void);

char *lez_multisig_list_proposals(const char *args_json);

char *lez_multisig_get_state(const char *args_json);

#endif  /* LEZ_MULTISIG_H */
